apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-env-config
data:
  # AWS configuration
  AWS_REGION: us-east-1
  AWS_BUCKET: udagram-bucket-2365
  URL: http://a7c43fff713d4440c8a4c1f76e49621f-538887260.us-east-1.elb.amazonaws.com:8100
  PORT: "8080"

  # JWT secret (non-confidential for example)
  JWT_SECRET: testing

  # Database host/dialect (non-sensitive)
  POSTGRES_HOST: cdr3.cxm6vlqhzoip.us-east-1.rds.amazonaws.com
  DB_DIALECT: postgres
